apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare
        image: chandanyadavks/gangabank
        ports:
        - containerPort: 8081
        env:
        - name: PORT
          value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare
spec:
  type: NodePort
  selector:
    app: healthcare  # <-- must match Deployment label
  ports:
  - port: 8082
    targetPort: 8082
    nodePort: 30085 # Optional: specify NodePort (default random 30000–32767)
